# Generated by Django 5.1.2 on 2025-01-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_contact_phone_number_alter_alert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
